### ISSUE TITLE
Support Travis

### ISSUE THREAD

**Issue by cgewecke** [codechecks/monorepo#1]
I know this is on your roadmap - if you're open to volunteers working on the client I'd love to help.

**Comment by krzkaczor** [comment]
Work on this would be highly appreciated! CircleCI implementation lies here: https://github.com/codechecks/monorepo/blob/master/packages/client/src/ci-providers/Circle.ts so you can use it as an inspiration. Also, note that there are dumps of fixtures in tests so I think it makes sense to add new ones for travis.

I never understood why Travis builds CI twice but I think on one of the builds we should just skip codechecks entirely. This might need some additional handling apart from implementing an interface. And of course, I assume that CI runs on merge commits.

**Comment by cgewecke** [comment]
Ok great, I will open a PR this week for this. Thanks!

**Comment by krzkaczor** [comment]
Closed by https://github.com/codechecks/monorepo/pull/12

**Comment by krzkaczor** [comment]
@all-contributors please add @cgewecke for code

**Comment by krzkaczor** [comment]
Thanks for all your help with this @cgewecke !
