### ISSUE TITLE
Can't get project slug for https repo origin

### ISSUE THREAD

**Issue by timocov** [codechecks/monorepo#23]
I think [this regex](https://github.com/codechecks/monorepo/blob/b16b8dae80518949199b33adfa74d08e33474187/packages/client/src/ci-providers/Local.ts#L6) should cover https-based origins as well.

**Comment by timocov** [comment]
Maybe we need to specify the project slug via config file only without checking git repo?

**Comment by krzkaczor** [comment]
@michalzalecki has hit the same bug. Were you working on a PR to fix it?

@timocov having the possibility to specify it in config seems like a good idea to me... Generally speaking, local mode needs to be redesign. I will write down my thought about this soon.

**Comment by MichalZalecki** [comment]
Correct @krzkaczor 👌 Will fix it tomorrow if not sooner. Sorry for the delay but other stuff came up.
