### ISSUE TITLE
Better error messages

### ISSUE THREAD

**Issue by krzkaczor** [codechecks/monorepo#32]
Currently, client will always print out only `error.message` which looks nice but is totally unpractical for unexpected errors. You need to use `DEBUG=codechecks:*` to get those. 

What would be desired is to have our subclass of errors something like `UserFacingError` which would print out a human-friendly error message. On unexpected errors, we should print out "ugly" error with full stack trace for debugging purposes.

CC: @MichalZalecki

**Comment by MichalZalecki** [comment]
@krzkaczor Would you consider moving away from OO approach to errors and go with the API similar to [boom](https://www.npmjs.com/package/boom)? It would centralize how we create new errors, making it easier to handle different types of errors depending on their context and also limit the number of classes.
