### ISSUE TITLE
Publish @codechecks/prettier-config

### ISSUE THREAD

**Issue by MichalZalecki** [codechecks/monorepo#39]
@krzkaczor It would be nice if plugin creators could reuse the config files for prettier (and also for linter, #38?).

**Comment by krzkaczor** [comment]
Have you seen [boilerplate](https://github.com/codechecks/boilerplate)? 

Other than that I wouldn't encourage plugin authors to use any specific config. Just pick whatever suits you 🤷‍♂ 

Reopen please if needed.

**Comment by MichalZalecki** [comment]
No, thanks for the link 👌
