### ISSUE TITLE
Docs for custom installation

### ISSUE THREAD

**Issue by DimitryDushkin** [codechecks/monorepo#66]
Hey!

Could you please provide some documentation on how to create and install own custom GitHub codechecks app on closed enterprise GitHub installation? Or just provide a link to GitHub app sources, I cannot find them.

**Comment by krzkaczor** [comment]
Hey! Sorry but this part is not yet open sourced. I am gonna let you know when it happens.

**Comment by DimitryDushkin** [comment]
I see. Thanks anyway.)
