### ISSUE TITLE
Question about speculative branches

### ISSUE THREAD

**Issue by cgewecke** [codechecks/monorepo#68]
Hi @krzkaczor :) hope all's well.

I'm missing historical data in a check installed on JoinColony/colonyNetwork. They use CircleCI and usually merge to `develop`. Their .yml looks like this: 
```
checks:
  - name: eth-gas-reporter/codechecks
settings:
  branches:
    - develop
    - master
```

Everything about the check looks correct (to me):
+ the [target and base][1] branches seem right. 
+ ci runs on [commit][2] 
+ no errors

**Log output**
```
CodeChecks Client v.0.1.10
https://codechecks.io

Executing 1 codechecks files
Base branch: 2a9ec03b

Executing codechecks.yml...

Checks: 1 succeeded, 1 total
Time:   2s
Done in 2.92s.
```

But nothing saves. An example of everything working perfectly on CircleCI can be seen at [omise-go/plasma-contracts][3]. They don't use speculative branching though. 

My codecheck code [looks like this][4].

Do you have any thoughts about why this might be / ideas for debugging it?

[1]: https://github.com/JoinColony/colonyNetwork/pull/749/checks?check_run_id=336054347
[2]: https://circleci.com/gh/JoinColony/colonyNetwork/tree/greenkeeper%2Feth-gas-reporter-0.2.14
[3]: https://github.com/omisego/plasma-contracts/pull/491/checks
[4]: https://github.com/cgewecke/eth-gas-reporter/blob/master/codechecks.js

**Comment by timocov** [comment]
Hey @cgewecke did you set up `CC_SECRET` env variable for your builds (see https://github.com/codechecks/docs/blob/master/getting-started.md)?

**Comment by cgewecke** [comment]
@timocov Ah thanks so much! That's very likely the problem. I'm not at joinColony, but just writing a tool they're using and I can't see their CI settings. Will chat with them about it though. 

Thanks! Closing.
