### ISSUE TITLE
Docs say you can use `codechecks.ts`, but settings are not read from it.

### ISSUE THREAD

**Issue by hasparus** [codechecks/monorepo#82]
Howdy 👋

See https://github.com/codechecks/monorepo/blob/ba52ad88a50898bf4ad246fd16ce5f7f7ada4034/packages/client/src/file-handling/settings.ts#L9 for settings implementation and https://github.com/codechecks/docs/blob/master/configuration.md#codecheckstsjs.

~~I'm interested in PRing `codechecks.ts` if it's still planned and not supported yet.~~

~~Outsourcing reading config to [cosmiconfig](https://github.com/davidtheclark/cosmiconfig) might be a fair approach.~~

After reading more of the code and implementing a bad hack I realize I might have misunderstood how `codechecks.ts` file is supposed to work — I assumed it returns a declarative config from `main` and you use it exactly the same way as `codechecks.yml`, but with autocomplete.

**Comment by krzkaczor** [comment]
Yes it works differently than declarative config files. It's a way to write custom checks as part of your project. Here's an example: https://github.com/Neufund/platform-frontend/blob/00986be35aeed96a9205670222200dccccbe0d64/packages/web/codechecks-vis-reg.ts

**Comment by hasparus** [comment]
Thanks!
